In [11]:
import csv
from bs4 import BeautifulSoup
import lxml
import urllib.request
import pandas

In [3]:
html=urllib.request.urlopen('https://karki23.github.io/Weather-Data/assignment.html').read()

In [5]:
obj=BeautifulSoup(html,'lxml')

In [9]:
web=[]
links=obj.find_all('a')
for i in links:
    web.append(i.get('href'))
print(web)

['Albury.html', 'BadgerysCreek.html', 'Cobar.html', 'CoffsHarbour.html', 'Moree.html', 'Newcastle.html', 'NorahHead.html', 'NorfolkIsland.html', 'Penrith.html', 'Richmond.html', 'Sydney.html', 'SydneyAirport.html', 'WaggaWagga.html', 'Williamtown.html', 'Wollongong.html', 'Canberra.html', 'Tuggeranong.html', 'MountGinini.html', 'Ballarat.html', 'Bendigo.html', 'Sale.html', 'MelbourneAirport.html', 'Melbourne.html', 'Mildura.html', 'Nhil.html', 'Portland.html', 'Watsonia.html', 'Dartmoor.html', 'Brisbane.html', 'Cairns.html', 'GoldCoast.html', 'Townsville.html', 'Adelaide.html', 'MountGambier.html', 'Nuriootpa.html', 'Woomera.html', 'Albany.html', 'Witchcliffe.html', 'PearceRAAF.html', 'PerthAirport.html', 'Perth.html', 'SalmonGums.html', 'Walpole.html', 'Hobart.html', 'Launceston.html', 'AliceSprings.html', 'Darwin.html', 'Katherine.html', 'Uluru.html']

In [13]:
counter=1
for k in web:
    h=urllib.request.urlopen('https://karki23.github.io/Weather-Data/'+ k).read()
    a=BeautifulSoup(h,'lxml')
    rows=[]
    t=a.find_all('table')
    for i in t:
        tr=i.find_all('tr')
        th=[j.text for j in tr[0].find_all('th')]
        rows.append(th)
        for m in tr[1:]:
            td=[l.text for l in m.find_all('td')]
            rows.append(td)
    print(counter)
    with open('dataset.csv','a') as f:
        writer=csv.writer(f)
        for i in rows:
            writer.writerow(i)
    counter=counter+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [15]:
ds=pandas.read_csv('dataset.csv')
ds.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,2008-07-01,Melbourne,9.5,15.4,2.0,2.8,7.0,W,63.0,W,...,38.0,1006.8,1010.3,1.0,7.0,11.0,14.6,Yes,0.6,No
1,2008-07-02,Melbourne,11.0,14.5,0.6,5.2,4.0,W,63.0,W,...,52.0,1013.4,1016.2,7.0,4.0,11.8,13.7,No,1.4,Yes
2,2008-07-03,Melbourne,8.4,14.1,1.4,2.0,0.8,W,39.0,W,...,58.0,1024.8,1024.3,7.0,7.0,10.6,13.9,Yes,0.6,No
3,2008-07-04,Melbourne,9.1,14.5,0.6,1.8,4.2,E,19.0,NNW,...,49.0,1030.2,1029.0,7.0,6.0,10.2,13.1,No,0.0,No
4,2008-07-05,Melbourne,4.3,15.5,0.0,0.8,8.4,N,52.0,N,...,52.0,1028.9,1024.9,2.0,5.0,5.5,14.6,No,0.0,No